apiVersion: v1
kind: Service
metadata:
  name: flower-service
  labels:
    app: flower
spec:
  type: NodePort
  selector:
    app: flower
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000 # Specify any available port within range 30000–32767
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30001
    - protocol: TCP
      port: 8002
      targetPort: 8002
      nodePort: 30002
