apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-server
  namespace: undergrad-kmanasu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triton-server
  template:
    metadata:
      labels:
        app: triton-server
    spec:
      containers:
        - name: triton-server
          image: kmanasu/triton-server:latest
          args: ["tritonserver", "--model-repository=/models"]
          volumeMounts:
            - name: model-volume
              mountPath: /models
            - name: shm-volume
              mountPath: /dev/shm  # Mounting shared memory here
          ports:
            - containerPort: 8000  # gRPC
            - containerPort: 8001  # HTTP
            - containerPort: 8002  # Metrics
      volumes:
        - name: model-volume
          hostPath:
            path: /home/kmanasu/inference-experiment/triton/models  # Host path on the node
            type: Directory
        - name: shm-volume
          emptyDir:
            medium: "Memory"  # Use RAM for /dev/shm
            sizeLimit: "1Gi"  # Increase shared memory size, e.g., to 1Gi
