apiVersion: v1
kind: Service
metadata:
  name: triton-service
  namespace: undergrad-kmanasu
spec:
  selector:
    app: triton-server
  ports:
    - name: grpc
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080  # Exposes gRPC at node IP with port 30080
    - name: http
      protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30081  # Exposes HTTP at node IP with port 30081
    - name: metrics
      protocol: TCP
      port: 8002
      targetPort: 8002
      nodePort: 30082  # Exposes Metrics at node IP with port 30082
  type: NodePort
